apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: InternRFC-app-user
  template:
    metadata:
      labels:
        app: InternRFC-app-user
    spec:
      containers:
      - name: user-container
        image: 533267283761.dkr.ecr.eu-central-1.amazonaws.com/user
        ports:
        - containerPort: 3000
